name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update -y -qq && sudo apt install -y -qq libsnmp-dev gcc libc-dev
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint 
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.33.0
      - name: WriteGoList
        run: go list -json -m all > go.list
      - name: nancy
        uses: sonatype-nexus-community/nancy-github-action@main
        with:
          nancyCommand: sleuth --exclude-vulnerability CVE-2020-15114,CVE-2020-15136,CVE-2020-15115,CVE-2020-26160
      - name: Unit Tests
        run: |
          go test -race -cover -coverprofile=coverage.txt -covermode=atomic -cpu 1,2 -bench . -benchmem > test.log
          cat test.log
      - name: Failed Logs
        if: failure()
        run: |
          cat test.log
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

      # Publish benchmarks for the master branch only
      - name: Store Benchmark Result
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: rhysd/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: "go"
          # Where the output from the benchmark tool is stored
          output-file-path: test.log
          # Push and deploy GitHub pages branch automatically
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

      # Updating go report card for master branch only
      - name: GoReportCard
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: curl --fail --request POST "https://goreportcard.com/checks" --data "repo=github.com/timdrysdale/relay"
